### PR TITLE
Add teleop twist keyboard

### PR DESCRIPTION
**Pull request by usedhondacivic**
### Changelog

Add new extension

### CODE REVIEW

**Review by defunctzombie — APPROVED** [review]
Can you remove the changes to yarn.lock please.

**Comment by usedhondacivic** [comment]
@defunctzombie done. Any insight about the CI failure? Seems like all the other extensions are whitelisted in validate.ts. I'm not sure how to compress my extension, but happy to do so with guidance.

**Comment by jtbandes** [comment]
CI issue will be fixed by https://github.com/foxglove/extension-registry/pull/37

**Comment by defunctzombie** [comment]
@usedhondacivic If you update this PR to merge or rebase main it should pass CI and we can merge it.

**Comment by usedhondacivic** [comment]
@defunctzombie done :+1:

**Comment by defunctzombie** [comment]
Thank you!

**Pull request merged**
