### PR TITLE
Update nvblox plugin to 2.2.0

### PR DESCRIPTION
**Pull request by david-tingdahl-nvidia**
### Changelog
None

### Docs
None

### Description
- New version adds a message converter for `nvblox_msgs/VoxelBlockLayer` messages.
- The new version is backwards-compatible

### CODE REVIEW

**Comment by defunctzombie** [comment]
@david-tingdahl-nvidia There are a few lint errors - could you fix the one about using an outdated `create-foxglove-extension` package. We can take care of the other one about the hash.

**Comment by defunctzombie** [comment]
@david-tingdahl-nvidia ping

**Comment by david-tingdahl-nvidia** [comment]
Hi, will have a public link with the new version available soon.
//David

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by defunctzombie** [comment]
> Hi, will have a public link with the new version available soon.

Sounds good - give me a ping on this issue once it is ready.

**Comment by david-tingdahl-nvidia** [comment]
The public link is updated now. How can I retrigger the premerge check?

**Comment by defunctzombie** [comment]
@david-tingdahl-nvidia I re-ran the checks. You still have two CI errors. One might be solved by merging latest main into your PR, the other is an outdated sha on your extension.

**Comment by david-tingdahl-nvidia** [comment]
There's  a remaining  error on "foxglove-teleop-twist-keyboard" after rebasing on ToT

**Comment by defunctzombie** [comment]
@jtbandes Why are we seeing this lint error again? I thought we had resolved this when we added the extension raising the lint error.

**Comment by jtbandes** [comment]
The lint error is:

> Error: The following SHA should be removed from exemptExtensionSHAs: 90af3124c1a68ab5b9b5d3faa480d1c77c0dd902ac1c7a71dea3f445c2df7939

**Comment by defunctzombie** [comment]
@david-tingdahl-nvidia I can't make the change because the PR is from your fork but you need to remove this line: https://github.com/foxglove/extension-registry/blob/main/validate.ts#L40

We added some validation and excluded some extensions until they could be updated. Since yours is updated we don't need this exemption.

**Comment by defunctzombie** [comment]
@david-tingdahl-nvidia When this is ready for review please mark it as such. It is still draft.

**Pull request merged**
